### ISSUE TITLE
Review - Inventory Table, Dispense Medication

### ISSUE THREAD

**Issue by Chase-Lee-ui** [uh-cryptics/zeus-matrp#18]
## Overview

The focus for this code review will be centered around the Inventory Table page and Dispense Medication page.
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review issue-18

## Files to review

- [x] [InventoryTable.jsx](https://github.com/uh-cryptics/zeus-matrp/blob/main/app/imports/ui/components/InventoryInformation.jsx)
- [x] [DispenseMedication.jsx](https://github.com/uh-cryptics/zeus-matrp/blob/main/app/imports/ui/components/DispenseMedication.jsx)

## Checklists

- [Architecture](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-architecture-checklist)
- [Design](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-design-checklist)
- [Javascript](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-js-checklist)
- [React](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-react-checklist)
- [UI](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-ui-checklist)

## Due date

10/5/21; 12:00pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by cammoore** [comment]
## InventoryTable.jsx

L38 and L49. Complicated code that took me a while to understand what
is going on. Some comments might help.

## DispenseMedication.jsx

Might want to use Uniforms for the form. That way you can use a schema
to determine what fields are required.

L42 May want another `let collectionName` that is first set to
History.getCollectionName(). Then is set to
Medication.getCollectionName().

**Comment by lukemcd9** [comment]
### DispenseMedication.jsx
JS-05: Line 36, can use built in JavaScript find() function.
UI-02: Layout is a bit cutoff when on mobile screen sizes
ES-01: Some ESLint errors to be fixed
DE-06: Map function on line 11 isn't necessary
TA-02: Form does not have an acceptance test

### InventoryTable.jsx
UI-02: On mobile, table gets cut off 
DE-06: tableData function isn't very readable the conditional on line 64 can be replaced with a lodash function
TA-01: The page is lacking a isDisplayed() aceptance test.

**Comment by rabitz808** [comment]
## InventoryTable.jsx
- L13,56 ESLINT-01: Unused variable and constant
- UI-02: Cluttered on mobile devices

## DispenseMedication.jsx
- L11-32 Design-09: Duplicated code 
- L39 ESLINT-01: Es lint error
- UI-02: Cluttered on mobile devices if the screen is really small

need to implement testing for both

**Comment by sheenatorres** [comment]
## Inventory Table page:

DE-03: Line 13, deleting variable unused. This is because delete function is still being implemented.

ES-01: Just one ESLint error for unused variable.

TI-01: Has integrations tests, but not yet implemented.
TA-01,02: Need acceptance test for each page and form.

UI-02: Header tabs of table is in one row; should be in columns, which should put info in columns also.


## Dispense page:

DE-01: Duplicated code fragment at line 13; need to refractor to reduce duplication.

ES-01: Fix some ESLint errors. Other warnings are regarding the duplicated code fragments.

TI-01: Has integrations tests, but not yet implemented.
TA-01,02: Need acceptance tests for both forms.

UI-04: Maybe have example values for Clinic Location and Amount

**Comment by Chase-Lee-ui** [comment]
## Inventory Table
DE-03: Eliminate dead code, ES-01: No errors, avoid warnings
Delete is an unused variable

## Disapense Page
DE-02: Avoid deeply nested conditionals
Barely any nested conditionals but need it to display low products
Missing a semicolon; easily fixable

## Overall
UI-07: No errors in the console
There is one error in the console
Code is easy to read, implementation is intuitive
