### ISSUE TITLE
Review - AddMedication, DeleteMedication

### ISSUE THREAD

**Issue by Chase-Lee-ui** [uh-cryptics/zeus-matrp#38]
## Overview

The focus for this code review will be centered around the Add and Delete components
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review issue-38

## Files to review

- [x] [AddMedication.jsx](https://github.com/uh-cryptics/zeus-matrp/blob/main/app/imports/ui/components/AddMedication.jsx)
- [x] [DeleteMedication.jsx](https://github.com/uh-cryptics/zeus-matrp/blob/main/app/imports/ui/components/DeleteMedication.jsx)

## Checklists

- [Architecture](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-architecture-checklist)
- [Design](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-design-checklist)
- [Javascript](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-js-checklist)
- [React](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-react-checklist)
- [UI](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-ui-checklist)

## Due date

10/14/21; 12:00pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by lukemcd9** [comment]
## AddMedication.jsx
DE-05: The functional code on lines 10, 11, and 12 could use comments to explain what it's doing.
JS-03: Some form field props like on line 93 can use object destructuring like on line 92.
ES-01: Some ESLint errors that need to be fixed.

## DeleteMedication.jsx
DE-01: We could remove this file or DeleteSupply.jsx and pass a prop to determine which collection to delete from.
ES-01: ESLint errors that need to be fixed.
UI-07: Console generates when clicking outside of Modal.

**Comment by Chase-Lee-ui** [comment]
## AddMedication
When putting in an incorrect value in the add medication and putting in a new valid unit, it submits the unity which may
leave some misinterpretation by the user

Could possibly add a "donated from" input field

UI-04: Forms provide example values.
No example value for medication type

## DeleteMedication
Could possibly add a delete history and maybe a reason why they deleted something

ES-01: No errors, avoid warnings.
clear was used before it was defined

UI-03: Links, buttons, and other controllers are obvious.
On list inventory need a better GUI to find the component for delete medication

**Comment by deshay-clemons** [comment]
AddMedication
ES-01
- L6) moving import of sweet-alerts above the import of {defineMethod}
- L30) adding space between the opening and closing curly braces
- L37) moving clear arrow function before the submit arrow function 
- L96-97, L101-102, L118-119, L124-125) remove trailing spaces 
DeleteMedication
UI-07
- Console generates a warning when you click outside the delete confirmation, modal right before actually deleting. “Can't perform a React state update on an unmounted component…”
ES-01
- L20) adding spaces between the opening and closing curly braces
