### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Chase-Lee-ui** [uh-cryptics/zeus-matrp#42]
## Overview

The focus for this code review will be centered around the Dispense and Edit components
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review issue-50

## Files to review

- [x] [DispenseMedication](https://github.com/uh-cryptics/zeus-matrp/blob/main/app/imports/ui/components/DispenseMedication.jsx)
- [x] [EditMedication](https://github.com/uh-cryptics/zeus-matrp/blob/main/app/imports/ui/components/EditMedication.jsx)

## Checklists

- [Architecture](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-architecture-checklist)
- [Design](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-design-checklist)
- [Javascript](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-js-checklist)
- [React](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-react-checklist)
- [UI](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-ui-checklist)

## Due date

11/2/21; 12:00pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by lukemcd9** [comment]
## DispenseMedication.jsx
DE-05: Functional code on lines 12, 13, 14 could have comments to explain what it is doing.
JS-05: Some lodash functions can be replaced with built-in ES6 functions like on line 47.
DE-07: On lines 95 and 96 the clear function already does setOpen(false) so the call on line 95 is redundant

## EditMedication.jsx
DE-05: Functional code on lines 14 and 15 could have comments to explain what's happening.
ES-01: Some ESLint errors that need to be fixed.
JS-03: There are some places where object destructuring can be used.

**Comment by deshay-clemons** [comment]
DispenseMedication
- DE-05/06 L51) The code snippet I made might be a little convoluted to read and digest, but with the commenting above hopefully, that alleviates that issue.

Edit Medication
ES-01 (Mostly renaming variables to fix eslint warnings)
- L14) Have to rename ‘item’ to avoid conflict with the parameter item on line 11.
- L27) Have to rename ‘type’ to avoid conflict with the state variable type on line 18
- L34) Have to rename ‘error’ to avoid conflict with the state variable type on line 26

**Comment by Chase-Lee-ui** [comment]
## DispenseMedication
User can put in 0 or negative values which is not intended for the dispense function.
Only acceptable values should be positive and within the domain of available units
UI-03: Links, buttons, and other controllers are obvious.
When filling in the item box first it fulfills the LOT number and locks it, however user
can try and fill in lot number first when filling in the item field is the intended way.
Not exactly intuitive to user, maybe switching the two spots or making the LOT number disabled
to begin with. Or if filling in Lock number first it narrows down medication options to only
possible options. Or vise versa.

## EditMedication
UI-03: Links, buttons, and other controllers are obvious.
The button to get to the edit medication button is not too obvious since the table looks
unclickable
I don't believe that the medication name should be editable. Could also possible have notes
not be editable but the ability to add additional notes

**Comment by cammoore** [comment]
## DispenseMedication.jsx

Comments would help understanding complex conversion.
https://github.com/uh-cryptics/zeus-matrp/blob/eac2eba8247f58676dae8ec502c31d81b70ae813/app/imports/ui/components/DispenseMedication.jsx#L12

Work on meaningful variable names (e.g. item is actually the id).

Should this be the logged in user?
https://github.com/uh-cryptics/zeus-matrp/blob/eac2eba8247f58676dae8ec502c31d81b70ae813/app/imports/ui/components/DispenseMedication.jsx#L124

## EditMedication.jsx

Do we need the if (open)?
https://github.com/uh-cryptics/zeus-matrp/blob/eac2eba8247f58676dae8ec502c31d81b70ae813/app/imports/ui/components/EditMedication.jsx#L13

**Comment by jktang342** [comment]
### DispenseMedication

DE-05: Some comments on the large code chunks can help explain what the function does

TA-01: Testing needs to be made
TA-02: Testing needs to be made

### EditMedication

ES-01: Contains ESLint errors

TA-01: Testing needs to be made
TA-02: Testing needs to be made

UI-03: Edit button could be made more explicit
UI-07: Generates console errors when closing modal by clicking outside it

**Comment by sheenatorres** [comment]
## DispenseMedication.jsx

Architecture: Looks good.

Design: Could have some comments for readability.

Javascript: Looks good, name constructs of each variable makes code easy to understand.

ESLint: No major ESLint errors, but just weak warnings.

Meteor: Looks good.

React: Looks good.

Testing: Need acceptance testing since page is a form.

UI: Looks good.


## EditMedication.jsx

Architecture: Looks good.

Design: Maybe some comments for some functions.

Javascript: Looks good, name constructs of each variable makes code easy to understand.

ESLint: Some ESLint errors.

Meteor: Looks good.

React: Looks good.

Testing: Need acceptance testing since page is a form.

UI: Format out of place between LOT and item when in mobile view.
